/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ali
 */import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Shop extends javax.swing.JFrame {
 
    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Loop through rows and remove them one by one
    while (model.getRowCount() > 0) {
        model.removeRow(0);
    }

    // Repaint table view
    jTable1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 790, 96, 40));

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Checkout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 710, 123, 40));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1apple.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 73, 73));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_2371560.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 80, 70));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1delicious-banana.jpg"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, -1, 73));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_guava-g20fd271ad_640.png"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, -1, 73));

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_usb.png"))); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 73));

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_iphone14.png"))); // NOI18N
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 73));

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1ipad.png"))); // NOI18N
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 73));

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_mac.png"))); // NOI18N
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, 73));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_2earphones-ge720d00b7_1920.jpg"))); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, 73));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_samsung.jpg"))); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 73));

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1hplaptop.jpg"))); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, 73));

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_shutterstock_459214822.jpg"))); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, 73));

        b13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1earbuds.jpg"))); // NOI18N
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, 73));

        b14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_gaming_pc.jpg"))); // NOI18N
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 73));

        b15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_airpods.png"))); // NOI18N
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 73));

        b16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1keyboard.jpg"))); // NOI18N
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 73));

        l1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Apple");
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 760, 73, -1));

        l3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Mango");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, 73, -1));

        l7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("Guava");
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 760, 73, -1));

        l5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("Banana");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 760, 100, -1));

        l13.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l13.setText("Laptop");
        getContentPane().add(l13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 90, -1));

        l15.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l15.setText("AC");
        getContentPane().add(l15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 73, -1));

        l11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l11.setText("Mobile");
        getContentPane().add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 90, -1));

        l9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("Earphone");
        l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 120, -1));

        l27.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l27.setText("Gaming pc");
        l27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, -1));

        l29.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l29.setText("Airpod");
        getContentPane().add(l29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 80, -1));

        l25.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l25.setText("Earbud");
        getContentPane().add(l25, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 400, 90, -1));

        l31.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l31.setText("KeyBoard");
        l31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, -1));

        l23.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l23.setText("Mac");
        getContentPane().add(l23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 73, -1));

        l21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l21.setText("Ipad");
        l21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 73, -1));

        l19.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l19.setText("Iphone");
        getContentPane().add(l19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, -1));

        l17.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l17.setText("USB 1tb");
        getContentPane().add(l17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 100, -1));

        l2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("20");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, 73, -1));

        l4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("40");
        l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 800, 73, -1));

        l6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("90");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 800, 73, -1));

        l8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("10");
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 73, -1));

        l10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("100");
        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 73, -1));

        l12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l12.setText("300");
        getContentPane().add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 73, -1));

        l14.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.setText("700");
        getContentPane().add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 73, -1));

        l16.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.setText("398");
        l16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 73, -1));

        l18.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l18.setText("20");
        l18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 73, -1));

        l20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l20.setText("800");
        getContentPane().add(l20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 73, -1));

        l22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l22.setText("500");
        l22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 73, -1));

        l24.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l24.setText("2000");
        getContentPane().add(l24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 73, -1));

        l26.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l26.setText("20");
        getContentPane().add(l26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 73, -1));

        l28.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l28.setText("1500");
        getContentPane().add(l28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 73, -1));

        l30.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l30.setText("200");
        l30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(l30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 73, 20));

        l32.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l32.setText("200");
        getContentPane().add(l32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 73, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel36.setText("Total price");

        jTextField1.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(255, 153, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Cart");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 720, 90, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cash Paid");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Product");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Shelves.jpg"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTextField2.setText(jTextField1.getText());  

    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed


String productName = l1.getText();
    String price = l2.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));
        

        
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int selectedRow = jTable1.getSelectedRow();

        // Check if a row is selected
        // Check if a row is selected
if (selectedRow != -1) {
    // Get the price of the selected row
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    double price = Double.parseDouble(model.getValueAt(selectedRow, 1).toString());

    // Subtract the price from the total
    double total = Double.parseDouble(jTextField1.getText());
    total -= price;
    jTextField1.setText(String.format("%.2f", total));

    // Remove the selected row from the table model
    model.removeRow(selectedRow);
}    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
String productName = l3.getText();
    String price = l4.getText();
   
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
String productName = l5.getText();
    String price = l6.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
String productName = l7.getText();
    String price = l8.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
String productName = l9.getText();
    String price = l10.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
String productName = l11.getText();
    String price = l12.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
String productName = l13.getText();
    String price = l14.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
String productName = l15.getText();
    String price = l16.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
String productName = l17.getText();
    String price = l18.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
String productName = l19.getText();
    String price = l20.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
String productName = l21.getText();
    String price = l22.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
String productName = l23.getText();
    String price = l24.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
String productName = l25.getText();
    String price = l26.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
String productName = l27.getText();
    String price = l28.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
String productName = l29.getText();
    String price = l30.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
String productName = l31.getText();
    String price = l32.getText();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Add row to table model
    model.addRow(new Object[]{productName, price});

    // Calculate sum of values in the "Price" column
    double sum = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        sum += value;
    }

    // Display sum in text field
    jTextField1.setText(Double.toString(sum));
   
// TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l28;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
